apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name:  generic-build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git

    params:
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/vote

      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/vote/Dockerfile

  outputs:
    resources:
      - name: destImage
        type: image

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --context=${inputs.params.pathToContext}
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.destImage.url}
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
