apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: voting-api-pipelinerun
spec:
  pipelineRef:
    name: generic-cicd-pipeline
  resources:
   - name: git-source
     resourceRef:
        name: voting-ui-vote

   - name: pipeline-built-image
      resourceRef:
        name: result-ui

   - name: pipeline-source-repo-cicd
      resourceRef:
        name: voting-ui-vote

 params:
    - name: p-pathToDockerFile
      value: Dockerfile

    - name: p-pathToContext
      value: /workspace/git-source

    - name: p-yamlFile
      value: "manifest/deployment.yaml"

    - name: p-yamlImagePath
      value: "spec.template.spec.containers[0].image"

    - name: p-yamls
      value: "manifest"
