apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: voting-ui-vote
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/vijesh-v/example-voting-app